# Apply PostgreSQL configuration files and restart if needed
---
# - name: Set OS-specific variables
#   set_fact:
#     _pg_config_dir: "{{ postgresql_config_dir }}"
#     _pg_service: "{{ 'postgresql' if ansible_os_family == 'Debian' else 'postgresql-' + postgresql_version }}"

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Reset PostgreSQL default password
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: postgres
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"

# - name: Ensure PostgreSQL log directory exists.
#   file:
#     path: "{{ postgresql_effective_log_dir }}"
#     owner: postgres
#     group: postgres
#     state: directory
#     mode: 0700

# - name: Deploy postgresql.conf
#   template:
#     src: postgresql.conf.j2
#     dest: "{{ postgresql_config_dir }}/postgresql.conf"
#     owner: "{{ postgresql_user }}"
#     group: "{{ postgresql_group }}"
#     mode: '0644'
#     backup: true
#   notify: restart postgresql

- name: Deploy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_config_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: '0640'
    backup: true
  notify: reload postgresql

# - name: Check PostgreSQL cluster status
#   become: true
#   become_user: postgres
#   command: "pg_lscluster {{ postgresql_version }} main"
#   register: pg_cluster
#   changed_when: false
#   when: ansible_os_family == "Debian"

- name: Verify installation
  include_tasks: "verify.yml"