# Testing if configuration requirements are set
---
- name: Pretest PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ DB_ROOT_ROLE }}"
    group: "{{ DB_ROOT_ROLE }}"
    state: directory
    mode: 0700

- name: Pretest PostgreSQL log directory exists.
  file:
    path: "{{ postgresql_data_dir }}/{{ postgresql_log_directory }}"
    owner: postgres
    group: postgres
    state: directory
    mode: 0700
...