airflow_home: "/opt/airflow"
airflow_venv: "{{ airflow_home }}/.venv"
airflow_dags: "{{ airflow_home }}/dags"
airflow_logs: "{{ airflow_home }}/logs"

airflow_user: airflow
airflow_group: airflow

airflow_celery_concurrency: 2
airflow_api_server_port: 8080