"all":
  "children":
    "dbserver":
      "hosts":
        "aws-iac-pipline-dev-dbserver-instance":
          "ansible_host": "18.199.102.90"
          "az": "eu-central-1a"
          "instance_id": "i-083dfff9de99bd604"
          "private_ip": "10.10.28.140"
          "public_ip": "18.199.102.90"
      "vars":
        "postgres_port": "5432"
        "postgresql_version": "16"
  "vars":
    "ansible_python_interpreter": "/usr/bin/python3"
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"
    "ansible_ssh_private_key_file": "./../ansible/keys/ansible-key.pem"
    "ansible_user": "ubuntu"
    #"environment": "dev"
    "project": "aws-iac-pipline"
    "region": "eu-central-1"
