# Configure Airflow
---
- name: Configure Airflow
  hosts: appserver
  become: true
  become_user: "{{ airflow_user }}"
  vars_files:
    - ../group_vars/terraform_vars.yml
  roles:
    - role: airflow_config
...
