# Configure PostgreSQL on database servers
---
- name: Configure PostgreSQL
  hosts: dbserver
  become: true
  roles:
  - role: postgresql_config
    # vars:
    #   postgresql_hba_entries:
    #     - type: host
    #       database: all
    #       user: all
    #       address: "18.199.102.90/32"