# Install PostgreSQL on database servers
---
- name: Install PostgreSQL
  hosts: dbserver
  vars_files:
    - ../group_vars/terraform_vars.yml
  become: true
  roles:
    - role: postgresql_install
...
