#!/bin/bash
set -e

# load env vars
source .env.psql

# connect with SSL required
# role: root
export PGSSLMODE=require
export PGPASSWORD=${DB_ROOT_PASS}
psql --host ${DB_HOST_PUBLIC} --port ${DB_PORT} --username ${DB_ROOT_ROLE} --dbname ${DB_ROOT_NAME} --no-password <<-EOSQL

\conninfo
\timing

CREATE ROLE ${DB_ADMIN_ROLE} WITH
    LOGIN
    PASSWORD '${DB_ADMIN_PASS}'
    NOCREATEDB
    NOSUPERUSER
    NOCREATEROLE
    NOINHERIT
    NOBYPASSRLS
    NOREPLICATION
    VALID UNTIL 'infinity'
    CONNECTION LIMIT ${DB_ADMIN_CONN_LIMIT};

CREATE ROLE ${DB_READ_ROLE} WITH
    LOGIN
    PASSWORD '${DB_READ_PASS}'
    NOCREATEDB
    NOSUPERUSER
    NOCREATEROLE
    NOINHERIT
    NOBYPASSRLS
    NOREPLICATION
    VALID UNTIL 'infinity'
    CONNECTION LIMIT ${DB_READ_CONN_LIMIT};

CREATE DATABASE ${DB_NAME} WITH
    OWNER ${DB_ADMIN_ROLE}
    ENCODING='UTF8'
    LC_COLLATE='en_US.UTF-8'
    LC_CTYPE='en_US.UTF-8'
    TEMPLATE template0;

\connect ${DB_NAME}

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA} AUTHORIZATION ${DB_ADMIN_ROLE};
SET search_path TO ${DB_SCHEMA};

CREATE EXTENSION IF NOT EXISTS dblink WITH
  SCHEMA ${DB_SCHEMA}
  VERSION '1.2';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH
  SCHEMA ${DB_SCHEMA};
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH
  SCHEMA ${DB_SCHEMA};

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_ADMIN_ROLE};
GRANT ALL ON SCHEMA ${DB_SCHEMA} TO ${DB_ADMIN_ROLE};

GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_READ_ROLE};
GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_READ_ROLE};
ALTER DEFAULT PRIVILEGES
  FOR ROLE ${DB_ADMIN_ROLE} IN SCHEMA ${DB_SCHEMA}
      GRANT SELECT ON TABLES TO ${DB_READ_ROLE};
ALTER DEFAULT PRIVILEGES
  FOR ROLE ${DB_ADMIN_ROLE} IN SCHEMA ${DB_SCHEMA}
      GRANT SELECT ON SEQUENCES TO ${DB_READ_ROLE};

-- List roles
\du
-- List databases
\l
-- List schemas
\dn+

\q
EOSQL