# Testing PostgreSQL installation is correct
---
- name: Test PostgreSQL version
  command: "psql --version"
  register: pg_version
  changed_when: false

- name: Display installed version
  debug:
    msg: "{{ pg_version.stdout }}"

- name: Test PostgreSQL connections
  become: true
  become_user: postgres
  command: "psql -c 'SELECT version();'"
  register: pg_connection
  changed_when: false

- name: Display server version
  debug:
    msg: "{{ pg_connection.stdout }}"

- name: Test PostgreSQL service status
  systemd:
    name: "{{ postgresql_service_name }}"
  register: pg_service

- name: Test service is active
  assert:
    that:
      - pg_service.status.ActiveState == "active"
    fail_msg: "PostgreSQL service is not running"