name: CopyToS3
on:
  push
env:
  AWS_REGION: eu-central-1
  AWS_ROLE: arn:aws:iam::508948847810:role/aws-iac-pipline-global-github-actions-role
  BUCKET_NAME : aws-iac-pipline-global-terraform-backend
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  S3Upload:
    runs-on: ubuntu-latest
    steps:
      - name: GIT clone Repository
        uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Copy README to s3
        run: |
          aws s3 cp ./README.md s3://${{ env.BUCKET_NAME }}/