name: Terraform deploy AWS infrastructure

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - "docs/**"
  workflow_dispatch

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: 1.15.8
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
  AWS_ROLE_SESSION_NAME: GitHub_to_AWS_via_FederatedOIDC
  WORK_DIR: terraform
  # tfvars
  # TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  # TF_VAR_environment: ${{ vars.ENVIRONMENT }}
  # TF_VAR_instance_type: ${{ vars.INSTANCE_TYPE }}
  # TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:

  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - name: GIT clone repository
        uses: actions/checkout@v6

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init without backend
        run: terraform init -backend=false

      - name: Terraform format code
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

  terraform-security:
    runs-on: ubuntu-latest
    steps:
      - name: GIT clone repository
        uses: actions/checkout@v6

      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORK_DIR }}

  terraform-plan:
    needs: [terraform-validate] # , terraform-security
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - name: GIT clone repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: terraform init

      - name: Create terraform.tfvars
        run: |
          cat > terraform.tfvars <<EOF
          ${{ secrets.TFVARS }}
          EOF

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -var-file=terraform.tfvars -out=tfplan
        continue-on-error: true

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v7
        with:
          name: tfplan
          path: ${{ env.WORK_DIR }}/tfplan

      - name: Comment plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `### Terraform Plan
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output.slice(0, 65000)
            });

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - name: GIT clone repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: terraform init

      - name: Download tfplan artifact
        uses: actions/download-artifact@v8
        with:
          name: tfplan
          path: ${{ env.WORK_DIR }}/

      - name: Terraform apply
        run: terraform apply --auto-approve tfplan

      - name: Upload artifact terraform_vars
        uses: actions/upload-artifact@v7
        with:
          name: terraform-vars
          path: artifacts/terraform_vars.yml

      - name: Upload artifact hosts
        uses: actions/upload-artifact@v7
        with:
          name: hosts
          path: artifacts/hosts.yml

      - name: Upload artifact env psql
        uses: actions/upload-artifact@v7
        with:
          name: env-psql
          path: artifacts/.env.psql